"use strict";
const {randomId}=require("./crypto");
function createPgStore(databaseUrl){
  if(!databaseUrl)throw new Error("DATABASE_URL_required");
  const {Pool}=require("pg");
  const pool=new Pool({connectionString:databaseUrl,ssl:databaseUrl.includes("localhost")?false:{rejectUnauthorized:false},max:8,idleTimeoutMillis:10000,connectionTimeoutMillis:8000});
  const q=(text,params=[])=>pool.query(text,params);
  return{
    async health(){const r=await q("select now() as now");return{ok:true,dbTime:r.rows[0].now};},
    async createUser({email,passwordHash,displayName,role}){const id=randomId("usr");const r=await q(`insert into ghz_users(id,email,password_hash,display_name,role) values($1,$2,$3,$4,$5) returning id,email,display_name as "displayName",role,created_at as "createdAt"`,[id,email,passwordHash,displayName,role]);return r.rows[0];},
    async getUserByEmail(email){const r=await q(`select id,email,password_hash as "passwordHash",display_name as "displayName",role,created_at as "createdAt",updated_at as "updatedAt" from ghz_users where email=$1 and disabled_at is null`,[email]);return r.rows[0]||null;},
    async getUserById(id){const r=await q(`select id,email,display_name as "displayName",role,created_at as "createdAt",updated_at as "updatedAt" from ghz_users where id=$1 and disabled_at is null`,[id]);return r.rows[0]||null;},
    async updateProfile(id,input){const r=await q(`update ghz_users set display_name=coalesce($2,display_name),updated_at=now() where id=$1 returning id,email,display_name as "displayName",role,updated_at as "updatedAt"`,[id,input.displayName||null]);return r.rows[0]||null;},
    async saveRefreshToken({hash,userId,expiresAt,deviceId}){await q(`insert into ghz_refresh_tokens(token_hash,user_id,expires_at,device_id) values($1,$2,$3,$4)`,[hash,userId,expiresAt,deviceId||null]);},
    async getRefreshToken(hash){const r=await q(`select token_hash as hash,user_id as "userId",expires_at as "expiresAt",revoked_at as "revokedAt" from ghz_refresh_tokens where token_hash=$1`,[hash]);return r.rows[0]||null;},
    async revokeRefreshToken(hash){await q(`update ghz_refresh_tokens set revoked_at=now() where token_hash=$1 and revoked_at is null`,[hash]);},
    async replaceRefreshToken(oldHash,next){const c=await pool.connect();try{await c.query("begin");const r=await c.query(`select user_id,expires_at,revoked_at from ghz_refresh_tokens where token_hash=$1 for update`,[oldHash]);const row=r.rows[0];if(!row||row.revoked_at||new Date(row.expires_at)<=new Date()){await c.query("rollback");return null;}await c.query(`update ghz_refresh_tokens set revoked_at=now(),replaced_by=$2 where token_hash=$1`,[oldHash,next.hash]);await c.query(`insert into ghz_refresh_tokens(token_hash,user_id,expires_at,device_id) values($1,$2,$3,$4)`,[next.hash,row.user_id,next.expiresAt,next.deviceId||null]);await c.query("commit");return{userId:row.user_id};}catch(e){await c.query("rollback");throw e;}finally{c.release();}},
    async getProgress(userId,profileId){const r=await q(`select profile_id as "profileId",version,data,updated_at as "updatedAt" from ghz_progress where user_id=$1 and profile_id=$2`,[userId,profileId]);return r.rows[0]||{profileId,version:0,data:{},updatedAt:null};},
    async syncProgress(userId,profileId,baseVersion,data,deviceId){const c=await pool.connect();try{await c.query("begin");const r=await c.query(`select version,data,updated_at from ghz_progress where user_id=$1 and profile_id=$2 for update`,[userId,profileId]);if(!r.rows[0]){if(Number(baseVersion||0)!==0){await c.query(`insert into ghz_progress_conflicts(id,user_id,profile_id,client_version,server_version,client_data,server_data,device_id) values($1,$2,$3,$4,0,$5,'{}',$6)`,[randomId("cnf"),userId,profileId,baseVersion,data,deviceId||null]);await c.query("commit");return{conflict:true,server:{profileId,version:0,data:{}}};}const ins=await c.query(`insert into ghz_progress(user_id,profile_id,version,data,device_id) values($1,$2,1,$3,$4) returning profile_id as "profileId",version,data,updated_at as "updatedAt"`,[userId,profileId,data,deviceId||null]);await c.query("commit");return{conflict:false,server:ins.rows[0]};}const cur=r.rows[0];if(Number(baseVersion)!==Number(cur.version)){await c.query(`insert into ghz_progress_conflicts(id,user_id,profile_id,client_version,server_version,client_data,server_data,device_id) values($1,$2,$3,$4,$5,$6,$7,$8)`,[randomId("cnf"),userId,profileId,baseVersion,cur.version,data,cur.data,deviceId||null]);await c.query("commit");return{conflict:true,server:{profileId,version:cur.version,data:cur.data,updatedAt:cur.updated_at}};}const up=await c.query(`update ghz_progress set version=version+1,data=$3,device_id=$4,updated_at=now() where user_id=$1 and profile_id=$2 returning profile_id as "profileId",version,data,updated_at as "updatedAt"`,[userId,profileId,data,deviceId||null]);await c.query("commit");return{conflict:false,server:up.rows[0]};}catch(e){await c.query("rollback");throw e;}finally{c.release();}},
    async listConflicts(userId,profileId){const r=await q(`select id,profile_id as "profileId",client_version as "clientVersion",server_version as "serverVersion",client_data as "clientData",server_data as "serverData",created_at as "createdAt" from ghz_progress_conflicts where user_id=$1 and ($2::text is null or profile_id=$2) order by created_at desc limit 50`,[userId,profileId||null]);return r.rows;},
    async listClasses(userId){const r=await q(`select c.id,c.name,c.code,c.teacher_id as "teacherId",c.created_at as "createdAt" from ghz_classes c left join ghz_class_members m on m.class_id=c.id where c.teacher_id=$1 or m.user_id=$1 group by c.id order by c.created_at desc`,[userId]);return r.rows;},
    async createClass(userId,input){const id=randomId("cls"),code=(Math.random().toString(36).slice(2,8)).toUpperCase();const r=await q(`insert into ghz_classes(id,name,code,teacher_id) values($1,$2,$3,$4) returning id,name,code,teacher_id as "teacherId",created_at as "createdAt"`,[id,input.name,code,userId]);return r.rows[0];},
    async joinClass(userId,code){const r=await q(`select id,name,code,teacher_id as "teacherId" from ghz_classes where code=$1 and archived_at is null`,[code]);const klass=r.rows[0];if(!klass)return null;await q(`insert into ghz_class_members(class_id,user_id) values($1,$2) on conflict do nothing`,[klass.id,userId]);return klass;},
    async listAssignments(userId){const r=await q(`select a.id,a.class_id as "classId",a.teacher_id as "teacherId",a.title,a.instructions,a.due_at as "dueAt",a.items,a.created_at as "createdAt" from ghz_assignments a join ghz_classes c on c.id=a.class_id left join ghz_class_members m on m.class_id=c.id and m.user_id=$1 where c.teacher_id=$1 or m.user_id=$1 order by a.created_at desc limit 200`,[userId]);return r.rows;},
    async createAssignment(userId,input){const id=randomId("asg");const r=await q(`insert into ghz_assignments(id,class_id,teacher_id,title,instructions,due_at,items) select $1,$2,$3,$4,$5,$6,$7 where exists(select 1 from ghz_classes where id=$2 and teacher_id=$3 and archived_at is null) returning id,class_id as "classId",teacher_id as "teacherId",title,instructions,due_at as "dueAt",items,created_at as "createdAt"`,[id,input.classId,userId,input.title,input.instructions||"",input.dueAt||null,input.items||[]]);return r.rows[0]||null;},
    async listSubmissions(userId){const r=await q(`select s.id,s.assignment_id as "assignmentId",s.student_id as "studentId",s.answers,s.status,s.submitted_at as "submittedAt",s.updated_at as "updatedAt" from ghz_submissions s join ghz_assignments a on a.id=s.assignment_id where s.student_id=$1 or a.teacher_id=$1 order by s.updated_at desc limit 300`,[userId]);return r.rows;},
    async upsertSubmission(userId,input){const id=input.id||randomId("sub");const r=await q(`insert into ghz_submissions(id,assignment_id,student_id,answers,status,submitted_at) select $1,$2,$3,$4,$5,case when $5='submitted' then now() else null end where exists(select 1 from ghz_assignments a join ghz_class_members m on m.class_id=a.class_id where a.id=$2 and m.user_id=$3) on conflict(assignment_id,student_id) do update set answers=excluded.answers,status=excluded.status,submitted_at=case when excluded.status='submitted' then now() else ghz_submissions.submitted_at end,updated_at=now() returning id,assignment_id as "assignmentId",student_id as "studentId",answers,status,submitted_at as "submittedAt",updated_at as "updatedAt"`,[id,input.assignmentId,userId,input.answers||{},input.status||"in_progress"]);return r.rows[0]||null;},
    async listGrades(userId){const r=await q(`select g.id,g.submission_id as "submissionId",g.grade,g.rubric,g.comment,g.created_at as "createdAt" from ghz_grades g join ghz_submissions s on s.id=g.submission_id join ghz_assignments a on a.id=s.assignment_id where s.student_id=$1 or a.teacher_id=$1 order by g.created_at desc limit 300`,[userId]);return r.rows;},
    async gradeSubmission(userId,input){const id=randomId("grd");const r=await q(`insert into ghz_grades(id,submission_id,teacher_id,grade,rubric,comment) select $1,$2,$3,$4,$5,$6 from ghz_submissions s join ghz_assignments a on a.id=s.assignment_id where s.id=$2 and a.teacher_id=$3 on conflict(submission_id) do update set grade=excluded.grade,rubric=excluded.rubric,comment=excluded.comment,updated_at=now() returning id,submission_id as "submissionId",grade,rubric,comment,updated_at as "updatedAt"`,[id,input.submissionId,userId,input.grade,input.rubric||{},input.comment||""]);return r.rows[0]||null;},
    async listAnnouncements(userId){const r=await q(`select n.id,n.class_id as "classId",n.teacher_id as "teacherId",n.title,n.body,n.created_at as "createdAt" from ghz_announcements n join ghz_classes c on c.id=n.class_id left join ghz_class_members m on m.class_id=c.id and m.user_id=$1 where c.teacher_id=$1 or m.user_id=$1 order by n.created_at desc limit 200`,[userId]);return r.rows;},
    async createAnnouncement(userId,input){const id=randomId("ann");const r=await q(`insert into ghz_announcements(id,class_id,teacher_id,title,body) select $1,$2,$3,$4,$5 where exists(select 1 from ghz_classes where id=$2 and teacher_id=$3) returning id,class_id as "classId",teacher_id as "teacherId",title,body,created_at as "createdAt"`,[id,input.classId,userId,input.title||"GHAZAL",input.body]);return r.rows[0]||null;},
    async insertEvents(userId,events){for(const e of events.slice(0,100)){await q(`insert into ghz_events(id,user_id,name,payload,occurred_at) values($1,$2,$3,$4,$5)`,[randomId("evt"),userId,String(e.name||"unknown").slice(0,100),e.payload||{},e.occurredAt||new Date()]);}return{accepted:Math.min(events.length,100)};},
    async getEntitlements(userId){const r=await q(`select key,value,expires_at as "expiresAt" from ghz_entitlements where user_id=$1 and (expires_at is null or expires_at>now())`,[userId]);return r.rows;},
    async upsertPushToken(userId,input){await q(`insert into ghz_devices(id,user_id,platform,push_token,updated_at) values($1,$2,$3,$4,now()) on conflict(user_id,platform,push_token) do update set updated_at=now()`,[input.deviceId||randomId("dev"),userId,input.platform||"android",input.pushToken]);return{ok:true};},
    async getIdempotency(userId,key){const r=await q(`select status_code as "statusCode",response_body as body from ghz_idempotency where user_id=$1 and key=$2 and expires_at>now()`,[userId,key]);return r.rows[0]||null;},
    async putIdempotency(userId,key,statusCode,body){await q(`insert into ghz_idempotency(user_id,key,status_code,response_body,expires_at) values($1,$2,$3,$4,now()+interval '24 hours') on conflict(user_id,key) do nothing`,[userId,key,statusCode,body]);},
    async consumeRateLimit(subject,route,limit,windowSec){const bucket=Math.floor(Date.now()/1000/windowSec)*windowSec;const r=await q(`insert into ghz_rate_limits(subject,route,bucket_start,count) values($1,$2,to_timestamp($3),1) on conflict(subject,route,bucket_start) do update set count=ghz_rate_limits.count+1 returning count`,[subject,route,bucket]);return{allowed:Number(r.rows[0].count)<=limit,count:Number(r.rows[0].count),limit,resetAt:(bucket+windowSec)*1000};},
    async close(){await pool.end();}
  };
}
module.exports={createPgStore};
