"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),{EventEmitter}=require("events");
const {hashPassword,verifyPassword,signAccessToken,verifyAccessToken}=require("../backend/crypto");
const {createMemoryStore}=require("../backend/memory-store");
const {createApp}=require("../backend/app");
const config={env:"test",tokenSecret:"0123456789abcdef0123456789abcdef0123456789abcdef",accessTtl:900,refreshTtl:2592000,allowedOrigins:[],aiApiKey:"",aiBaseUrl:"https://api.openai.com/v1",aiModel:"gpt-5-mini",release:"test"};
function request(app,{method="GET",url="/",body,headers={}}={}){return new Promise((resolve,reject)=>{const req=new EventEmitter();req.method=method;req.url=url;req.headers=headers;req.socket={remoteAddress:"127.0.0.1"};req.destroy=()=>{};const out={headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},end(v=""){this.body=v;resolve({status:this.statusCode,headers:this.headers,json:v?JSON.parse(v):null});}};Promise.resolve(app(req,out)).catch(reject);process.nextTick(()=>{if(body!==undefined)req.emit("data",Buffer.from(JSON.stringify(body)));req.emit("end");});});}
async function register(app,email,role="student"){return request(app,{method:"POST",url:"/v1/auth/register",body:{email,password:"CorrectHorse42!",displayName:"Test User",role}});}
test("password hashing and access token verification are hardened",()=>{const h=hashPassword("CorrectHorse42!");assert.notEqual(h,"CorrectHorse42!");assert.equal(verifyPassword("CorrectHorse42!",h),true);assert.equal(verifyPassword("wrong-password",h),false);const t=signAccessToken({sub:"u1",role:"student"},config.tokenSecret,30);assert.equal(verifyAccessToken(t,config.tokenSecret).sub,"u1");assert.equal(verifyAccessToken(t,config.tokenSecret+"x"),null);});
test("register login refresh and authenticated profile path work",async()=>{const app=createApp({store:createMemoryStore(),config});const r=await register(app,"student@example.com");assert.equal(r.status,201);assert.ok(r.json.accessToken&&r.json.refreshToken);const me=await request(app,{url:"/v1/users/me",headers:{authorization:"Bearer "+r.json.accessToken}});assert.equal(me.status,200);assert.equal(me.json.user.email,"student@example.com");const rf=await request(app,{method:"POST",url:"/v1/auth/refresh",body:{refreshToken:r.json.refreshToken}});assert.equal(rf.status,200);assert.notEqual(rf.json.refreshToken,r.json.refreshToken);});
test("progress sync uses optimistic versioning and records conflicts",async()=>{const store=createMemoryStore(),app=createApp({store,config});const r=await register(app,"sync@example.com"),h={authorization:"Bearer "+r.json.accessToken,"x-idempotency-key":"sync-1"};const s1=await request(app,{method:"POST",url:"/v1/progress/sync",headers:h,body:{profileId:"p1",baseVersion:0,data:{xp:10},deviceId:"d1"}});assert.equal(s1.status,200);assert.equal(s1.json.server.version,1);const replay=await request(app,{method:"POST",url:"/v1/progress/sync",headers:h,body:{profileId:"p1",baseVersion:0,data:{xp:999}}});assert.equal(replay.status,200);assert.equal(replay.headers["x-idempotency-replayed"],"true");const conflict=await request(app,{method:"POST",url:"/v1/progress/sync",headers:{authorization:"Bearer "+r.json.accessToken},body:{profileId:"p1",baseVersion:0,data:{xp:20}}});assert.equal(conflict.status,409);assert.equal(conflict.json.server.version,1);});
test("teacher classroom flow is real and role-protected",async()=>{const store=createMemoryStore(),app=createApp({store,config});const teacher=await register(app,"teacher@example.com","teacher"),student=await register(app,"learner@example.com","student"),th={authorization:"Bearer "+teacher.json.accessToken},sh={authorization:"Bearer "+student.json.accessToken};const c=await request(app,{method:"POST",url:"/v1/classes",headers:th,body:{name:"B2 Migration"}});assert.equal(c.status,201);const j=await request(app,{method:"POST",url:"/v1/classes/join",headers:sh,body:{code:c.json.class.code}});assert.equal(j.status,200);const a=await request(app,{method:"POST",url:"/v1/assignments",headers:th,body:{classId:c.json.class.id,title:"Writing",items:[{kind:"writing",prompt:"Termin absagen"}]}});assert.equal(a.status,201);const s=await request(app,{method:"POST",url:"/v1/submissions",headers:sh,body:{assignmentId:a.json.assignment.id,answers:{a:"Ich kann heute nicht."},status:"submitted"}});assert.equal(s.status,200);const g=await request(app,{method:"POST",url:"/v1/grades",headers:th,body:{submissionId:s.json.submission.id,grade:87,rubric:{grammar:85},comment:"Gut"}});assert.equal(g.status,200);assert.equal(Number(g.json.grade.grade),87);});
test("content contract and AI endpoint fail closed without provider secret",async()=>{const app=createApp({store:createMemoryStore(),config});const r=await register(app,"content@example.com"),h={authorization:"Bearer "+r.json.accessToken};const m=await request(app,{url:"/v1/content/manifest",headers:h});assert.equal(m.status,200);assert.equal(m.json.manifest.schema,2);const ai=await request(app,{method:"POST",url:"/v1/ai/tutor",headers:h,body:{message:"Hallo"}});assert.equal(ai.status,503);assert.equal(ai.json.reason,"ai_provider_not_configured");});
