begin;
create table if not exists ghz_users(
  id text primary key,email text not null unique,password_hash text not null,display_name text not null,role text not null check(role in('student','teacher','admin')),
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),disabled_at timestamptz
);
create table if not exists ghz_refresh_tokens(token_hash text primary key,user_id text not null references ghz_users(id) on delete cascade,device_id text,expires_at timestamptz not null,revoked_at timestamptz,replaced_by text,created_at timestamptz not null default now());
create index if not exists ghz_refresh_user_idx on ghz_refresh_tokens(user_id,expires_at);
create table if not exists ghz_progress(user_id text not null references ghz_users(id) on delete cascade,profile_id text not null,version bigint not null default 1,data jsonb not null default '{}'::jsonb,device_id text,updated_at timestamptz not null default now(),primary key(user_id,profile_id));
create table if not exists ghz_progress_conflicts(id text primary key,user_id text not null references ghz_users(id) on delete cascade,profile_id text not null,client_version bigint not null,server_version bigint not null,client_data jsonb not null,server_data jsonb not null,device_id text,created_at timestamptz not null default now());
create index if not exists ghz_conflict_user_idx on ghz_progress_conflicts(user_id,profile_id,created_at desc);
create table if not exists ghz_classes(id text primary key,name text not null,code text not null unique,teacher_id text not null references ghz_users(id),created_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists ghz_class_members(class_id text not null references ghz_classes(id) on delete cascade,user_id text not null references ghz_users(id) on delete cascade,joined_at timestamptz not null default now(),primary key(class_id,user_id));
create table if not exists ghz_assignments(id text primary key,class_id text not null references ghz_classes(id) on delete cascade,teacher_id text not null references ghz_users(id),title text not null,instructions text not null default '',due_at timestamptz,items jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists ghz_submissions(id text primary key,assignment_id text not null references ghz_assignments(id) on delete cascade,student_id text not null references ghz_users(id),answers jsonb not null default '{}'::jsonb,status text not null default 'in_progress' check(status in('in_progress','submitted','graded')),submitted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(assignment_id,student_id));
create table if not exists ghz_grades(id text primary key,submission_id text not null unique references ghz_submissions(id) on delete cascade,teacher_id text not null references ghz_users(id),grade numeric(5,2) not null check(grade>=0 and grade<=100),rubric jsonb not null default '{}'::jsonb,comment text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists ghz_announcements(id text primary key,class_id text not null references ghz_classes(id) on delete cascade,teacher_id text not null references ghz_users(id),title text not null default 'GHAZAL',body text not null,created_at timestamptz not null default now());
create table if not exists ghz_events(id text primary key,user_id text not null references ghz_users(id) on delete cascade,name text not null,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null,created_at timestamptz not null default now());
create index if not exists ghz_events_user_idx on ghz_events(user_id,occurred_at desc);
create table if not exists ghz_entitlements(user_id text not null references ghz_users(id) on delete cascade,key text not null,value jsonb not null default 'true'::jsonb,expires_at timestamptz,primary key(user_id,key));
create table if not exists ghz_devices(id text primary key,user_id text not null references ghz_users(id) on delete cascade,platform text not null,push_token text not null,updated_at timestamptz not null default now(),unique(user_id,platform,push_token));
create table if not exists ghz_idempotency(user_id text not null references ghz_users(id) on delete cascade,key text not null,status_code integer not null,response_body jsonb not null,expires_at timestamptz not null,created_at timestamptz not null default now(),primary key(user_id,key));
create table if not exists ghz_rate_limits(subject text not null,route text not null,bucket_start timestamptz not null,count integer not null default 1,primary key(subject,route,bucket_start));
commit;
